name: Run PHPUnit tests

on: pull_request

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                laravel: [5.5.*, 5.8.*, 6.*, 8.*, 10.*]
                php: [7.3, 7.4, 8.0, 8.1]
                exclude:
                    - laravel: 5.5.*
                      php: 8.0
                    - laravel: 5.5.*
                      php: 8.1
                    - laravel: 5.8.*
                      php: 8.0
                    - laravel: 5.8.*
                      php: 8.1
                    - laravel: 6.*
                      php: 8.1
                    - laravel: 8.*
                      php: 8.1
                    - laravel: 10.*
                      php: 7.3
                    - laravel: 10.*
                      php: 7.4
                    - laravel: 10.*
                      php: 8.0

        name: PHP${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: xdebug2
                  tools: composer:1.10.22

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --dev
                  composer update --prefer-stable --prefer-dist --no-interaction --dev
                  composer dumpautoload

            - name: Execute tests
              run: vendor/bin/phpunit
